### ISSUE TITLE
Le menu déroulant ne se replie pas 

### ISSUE THREAD

**Issue by Wild-Track** [AAEIUTM/Site-Web#6]
Je ne comprend pas, pourtant hier tout semblait fonctionner à l'heure de mon café. Mais lorsque aujourd'hui je regarde à nouveau ce magnifique site PATATRAC je me rend compte que le menu ne se ferme plus. 
J'espère que cette information vous sera utile, et cette fonctionnalité me manque beacoup

**Comment by agerard57** [comment]
Fait.
